import type { Cuisine, FoodTag, Method, Prep, RecipeDef, Step } from "./types";

// Every recipe. Steps are what you actually do, in order; the engine turns
// your performance at each into texture and taste. `target` is the seasoning
// a good cook aims for. `source` says how you can come to know a recipe:
//   basic       everyone knows it
//   book        from a cookbook (Jabi Lake Mall bookshop)
//   npc         taught by someone (`from`)
//   class       from a cooking class
//   experiment  only by experimenting in your own kitchen
//   secret      rare: competitions, travel, special people

const chop = (label: string): Step => ({ kind: "prep", action: "chop", label });
const prep = (action: Prep, label: string): Step => ({ kind: "prep", action, label });
const cook = (method: Method, temp: number, minutes: number, label: string): Step => ({ kind: "cook", method, temp, minutes, label });
const season = (label = "Season to taste"): Step => ({ kind: "season", label });
const plate = (label = "Plate it up"): Step => ({ kind: "plate", label });
const n = (id: string, qty = 1) => ({ id, qty });

type T = { spice: number; salt: number; sweet: number; sour: number };
const t = (spice: number, salt: number, sweet: number, sour: number): T => ({ spice, salt, sweet, sour });

function R(
  id: string,
  name: string,
  icon: string,
  cuisine: Cuisine,
  course: RecipeDef["course"],
  needs: RecipeDef["needs"],
  steps: Step[],
  target: T,
  difficulty: number,
  serves: number,
  value: number,
  nutrition: number,
  tags: FoodTag[],
  eat: RecipeDef["eat"],
  source: RecipeDef["source"],
  more: Partial<RecipeDef> = {},
): RecipeDef {
  return { id, name, icon, cuisine, course, needs, steps, target, difficulty, serves, value, nutrition, tags, eat, source, ...more };
}

const NG: FoodTag[] = ["local"];
const FOREIGN: FoodTag[] = ["foreign"];

export const RECIPES: RecipeDef[] = [
  // ── Nigerian everyday ──
  R("rice_stew", "Rice and stew", "🍛", "Nigerian", "main", [n("rice", 2), n("tomato", 2), n("pepper"), n("onion"), n("beef"), n("veg_oil"), n("stock")],
    [chop("Slice the onions and peppers"), cook("blend", 0, 3, "Blend the tomatoes and peppers"), cook("fry", 170, 15, "Fry the stew base until the oil floats"), cook("boil", 100, 20, "Boil the rice"), season(), plate()],
    t(5, 5, 2, 2), 2, 4, 1500, 55, [...NG, "comfort", "meat"], { food: 45, energy: 5, stress: -2 }, "basic"),
  R("jollof", "Jollof rice", "🍛", "Nigerian", "main", [n("rice", 2), n("tomato", 2), n("pepper"), n("scotch_bonnet"), n("onion"), n("veg_oil"), n("stock")],
    [chop("Dice the onions"), cook("blend", 0, 3, "Blend tomatoes, peppers and ata rodo"), cook("fry", 175, 12, "Fry the pepper base till it's deep red"), cook("simmer", 110, 30, "Simmer the rice in the base, lid on"), season(), plate("Plate with fried plantain")],
    t(6, 5, 2, 2), 3, 4, 1800, 50, [...NG, "spicy", "comfort"], { food: 45, energy: 5, stress: -3 }, "basic", { extras: ["chicken", "plantain", "thyme", "curry"], blurb: "The party favourite. Everyone has an opinion on yours." }),
  R("fried_rice", "Nigerian fried rice", "🍚", "Nigerian", "main", [n("rice", 2), n("carrot"), n("green_beans"), n("onion"), n("curry"), n("chicken"), n("veg_oil"), n("stock")],
    [chop("Dice carrots and green beans"), cook("boil", 100, 15, "Parboil the rice"), cook("fry", 190, 10, "Stir-fry the vegetables and rice"), season(), plate()],
    t(3, 5, 1, 0), 3, 4, 2000, 60, [...NG, "comfort", "meat"], { food: 45, energy: 6 }, "book", { from: "Abuja Kitchen Bible" }),
  R("egusi", "Egusi soup", "🥣", "Nigerian", "soup", [n("egusi", 2), n("palm_oil"), n("spinach"), n("beef"), n("crayfish"), n("onion"), n("scotch_bonnet"), n("stock")],
    [chop("Shred the spinach"), prep("pound", "Grind the egusi"), cook("boil", 100, 25, "Cook the meat with stock"), cook("fry", 160, 10, "Fry the egusi in palm oil"), cook("simmer", 95, 15, "Simmer with the greens"), season(), plate("Serve with a swallow")],
    t(5, 5, 0, 1), 3, 5, 2200, 70, [...NG, "comfort", "meat"], { food: 40, energy: 6, health: 1 }, "npc", { from: "Mama" }),
  R("efo_riro", "Efo riro", "🥬", "Nigerian", "soup", [n("spinach", 2), n("pepper"), n("scotch_bonnet"), n("palm_oil"), n("locust_beans"), n("beef"), n("onion")],
    [chop("Chop the spinach"), cook("blend", 0, 3, "Blend the peppers coarsely"), cook("fry", 165, 10, "Fry the pepper with iru"), cook("simmer", 95, 8, "Fold in the greens, don't overcook"), season(), plate()],
    t(5, 5, 0, 0), 3, 4, 2000, 80, [...NG, "healthy", "meat"], { food: 38, energy: 7, health: 2 }, "npc", { from: "okafor" }),
  R("ogbono", "Ogbono soup", "🥣", "Nigerian", "soup", [n("ogbono", 2), n("okra"), n("palm_oil"), n("dried_fish"), n("crayfish"), n("stock")],
    [chop("Slice the okra"), cook("fry", 150, 5, "Dissolve the ogbono in hot palm oil"), cook("simmer", 95, 20, "Simmer until it draws"), season(), plate("Serve with eba")],
    t(4, 5, 0, 0), 2, 5, 1800, 65, [...NG, "seafood"], { food: 40, energy: 5 }, "book", { from: "Abuja Kitchen Bible" }),
  R("okra_soup", "Okra soup", "🥒", "Nigerian", "soup", [n("okra", 2), n("palm_oil"), n("fish"), n("crayfish"), n("onion"), n("scotch_bonnet")],
    [chop("Chop the okra fine"), cook("boil", 100, 15, "Cook the fish in seasoned stock"), cook("simmer", 95, 6, "Add okra, two minutes, not more"), season(), plate()],
    t(4, 5, 0, 0), 2, 4, 1700, 75, [...NG, "seafood", "healthy"], { food: 38, energy: 6, health: 1 }, "book", { from: "Abuja Kitchen Bible" }),
  R("pepper_soup", "Goat meat pepper soup", "🍲", "Nigerian", "soup", [n("goat", 2), n("pepper_soup_spice"), n("scotch_bonnet"), n("onion"), n("scent_leaf")],
    [chop("Cut the goat meat small"), cook("boil", 100, 40, "Boil with the pepper soup spice"), season(), plate("Finish with scent leaf")],
    t(8, 5, 0, 1), 2, 3, 2500, 70, [...NG, "spicy", "meat"], { food: 30, water: 15, energy: 5, stress: -6 }, "book", { from: "Abuja Kitchen Bible", blurb: "Good for a cold, a hangover and heartbreak." }),
  R("catfish_pepper_soup", "Point-and-kill catfish pepper soup", "🐟", "Nigerian", "soup", [n("catfish", 2), n("pepper_soup_spice"), n("scotch_bonnet"), n("onion"), n("scent_leaf"), n("stock")],
    [chop("Clean and cut the catfish"), cook("simmer", 95, 25, "Simmer gently so the fish holds"), season(), plate()],
    t(8, 5, 0, 1), 3, 3, 4000, 75, [...NG, "spicy", "seafood", "luxury"], { food: 30, water: 15, energy: 6, stress: -8 }, "class"),
  R("beans_plantain", "Ewa and dodo", "🫘", "Nigerian", "main", [n("beans", 2), n("plantain", 2), n("palm_oil"), n("onion"), n("scotch_bonnet")],
    [chop("Slice the plantain"), cook("pressure", 120, 25, "Cook the beans soft"), cook("deepfry", 175, 6, "Fry the plantain golden"), season(), plate()],
    t(4, 4, 3, 0), 2, 3, 1200, 70, [...NG, "vegetarian", "comfort", "cheap"], { food: 45, energy: 6 }, "basic"),
  R("moi_moi", "Moi moi", "🟠", "Nigerian", "side", [n("beans", 2), n("pepper"), n("onion"), n("eggs"), n("veg_oil"), n("crayfish")],
    [prep("peel", "Peel the beans"), cook("blend", 0, 4, "Blend smooth with peppers"), prep("mix", "Mix in oil and seasoning"), cook("steam", 100, 45, "Steam in leaves or tins"), season(), plate()],
    t(4, 5, 1, 0), 3, 5, 800, 70, [...NG, "vegetarian"], { food: 28, energy: 5 }, "book", { from: "Abuja Kitchen Bible" }),
  R("akara", "Akara", "🟤", "Nigerian", "breakfast", [n("beans", 2), n("onion"), n("scotch_bonnet"), n("veg_oil")],
    [prep("peel", "Peel the beans"), cook("blend", 0, 3, "Blend thick"), prep("mix", "Whip air into the batter"), cook("deepfry", 175, 8, "Fry spoonfuls till golden"), season(), plate("Serve hot with pap or bread")],
    t(5, 5, 0, 0), 2, 4, 600, 55, [...NG, "breakfast", "street", "vegetarian"], { food: 25, energy: 5 }, "book", { from: "Abuja Kitchen Bible" }),
  R("suya", "Suya", "🍢", "Nigerian", "snack", [n("suya_beef", 2), n("suya_spice"), n("onion"), n("tomato")],
    [chop("Slice the beef thin"), prep("marinate", "Rub with yaji"), cook("grill", 230, 12, "Grill over open flame, turn often"), season(), plate("Serve with onions and tomatoes in newspaper")],
    t(7, 5, 0, 0), 3, 3, 2500, 50, [...NG, "spicy", "street", "meat"], { food: 25, energy: 4, stress: -4 }, "npc", { from: "suya", blurb: "Mallam Sani's way, if he likes you." }),
  R("asun", "Asun (spicy goat)", "🌶️", "Nigerian", "snack", [n("goat", 2), n("scotch_bonnet"), n("onion"), n("veg_oil")],
    [chop("Cut the goat into bites"), cook("grill", 220, 15, "Smoke-grill the goat"), cook("fry", 180, 5, "Toss in fried pepper"), season(), plate()],
    t(9, 5, 0, 0), 3, 3, 3000, 50, [...NG, "spicy", "meat"], { food: 25, stress: -4 }, "experiment"),
  R("pounded_yam", "Pounded yam", "⚪", "Nigerian", "side", [n("yam", 2)],
    [prep("peel", "Peel the yam"), cook("boil", 100, 20, "Boil until soft"), prep("pound", "Pound until smooth and stretchy")],
    t(0, 0, 0, 0), 2, 3, 700, 45, [...NG, "comfort"], { food: 35, energy: 6 }, "basic"),
  R("eba", "Eba", "🟡", "Nigerian", "side", [n("cassava_flour", 2)],
    [cook("boil", 100, 3, "Boil water"), prep("mix", "Turn the garri into the water")],
    t(0, 0, 0, 0), 1, 2, 300, 30, [...NG, "cheap"], { food: 35, energy: 4 }, "basic"),
  R("yam_porridge", "Yam porridge (asaro)", "🍠", "Nigerian", "main", [n("yam", 2), n("palm_oil"), n("tomato"), n("pepper"), n("onion"), n("crayfish")],
    [prep("peel", "Peel and cube the yam"), cook("boil", 100, 15, "Boil with the pepper mix"), prep("pound", "Mash some yam to thicken"), season(), plate()],
    t(5, 5, 1, 1), 2, 3, 1200, 55, [...NG, "comfort"], { food: 42, energy: 6, stress: -2 }, "book", { from: "Abuja Kitchen Bible" }),
  R("boli", "Boli and groundnut", "🍌", "Nigerian", "snack", [n("plantain", 2), n("groundnut")],
    [prep("peel", "Peel the plantain"), cook("grill", 200, 15, "Roast over coals, turning")],
    t(0, 1, 4, 0), 1, 2, 500, 55, [...NG, "street", "vegetarian", "cheap"], { food: 25, energy: 4 }, "basic"),
  R("puff_puff", "Puff puff", "🟤", "Nigerian", "snack", [n("flour", 2), n("sugar"), n("yeast"), n("veg_oil")],
    [prep("mix", "Mix the batter"), cook("ferment", 30, 45, "Let it rise"), cook("deepfry", 170, 8, "Drop balls into hot oil")],
    t(0, 1, 6, 0), 2, 6, 400, 20, [...NG, "street", "sweet"], { food: 18, energy: 6, stress: -3 }, "book", { from: "Baking 101" }),
  R("chin_chin", "Chin chin", "🟫", "Nigerian", "snack", [n("flour", 2), n("sugar"), n("butter"), n("eggs"), n("milk")],
    [prep("knead", "Knead the dough"), chop("Cut into small cubes"), cook("deepfry", 165, 10, "Fry till crunchy")],
    t(0, 1, 6, 0), 2, 6, 500, 20, [...NG, "sweet", "street"], { food: 15, energy: 5, stress: -2 }, "book", { from: "Baking 101" }),
  R("meat_pie", "Meat pie", "🥧", "Nigerian", "baked", [n("flour", 2), n("butter"), n("beef"), n("potato"), n("carrot"), n("onion"), n("eggs")],
    [chop("Dice potato, carrot and onion"), cook("fry", 170, 10, "Cook the filling"), prep("knead", "Make the pastry"), cook("bake", 190, 30, "Bake until golden"), plate()],
    t(3, 4, 1, 0), 3, 6, 900, 45, [...NG, "baked", "meat"], { food: 25, energy: 4 }, "book", { from: "Baking 101" }),
  R("noodles_egg", "Indomie and egg", "🍜", "Nigerian", "main", [n("noodles"), n("eggs"), n("onion"), n("pepper"), n("veg_oil")],
    [chop("Slice onions and pepper"), cook("boil", 100, 4, "Cook the noodles"), cook("fry", 170, 3, "Fry the egg"), season(), plate()],
    t(4, 6, 1, 0), 1, 1, 900, 30, [...NG, "fast", "cheap", "comfort"], { food: 35, energy: 4, stress: -2 }, "basic"),
  R("egg_bread", "Fried egg and bread", "🍳", "Nigerian", "breakfast", [n("eggs", 2), n("bread"), n("onion"), n("veg_oil")],
    [chop("Slice the onion"), cook("fry", 160, 5, "Fry the eggs"), season(), plate()],
    t(3, 4, 0, 0), 1, 1, 700, 45, [...NG, "breakfast", "fast"], { food: 30, energy: 8 }, "basic"),
  R("tea", "Tea with milk", "🍵", "Nigerian", "drink", [n("tea"), n("sugar"), n("powdered_milk")],
    [cook("brew", 100, 4, "Boil water and steep")], t(0, 0, 5, 0), 1, 2, 300, 10, ["drink", "breakfast"], { food: 3, water: 30, energy: 4 }, "basic"),
  R("zobo", "Zobo", "🌺", "Nigerian", "drink", [n("zobo_leaf"), n("ginger"), n("pineapple"), n("sugar")],
    [chop("Chop the pineapple and ginger"), cook("boil", 100, 20, "Boil the leaves with fruit"), season("Sweeten to taste")],
    t(1, 0, 6, 5), 1, 6, 400, 30, [...NG, "drink", "healthy"], { food: 2, water: 40, energy: 3 }, "book", { from: "Abuja Kitchen Bible" }),
  R("kunu", "Kunu", "🥛", "Nigerian", "drink", [n("kunu_millet"), n("ginger"), n("sugar")],
    [prep("pound", "Grind the millet with ginger"), cook("ferment", 30, 120, "Leave it overnight"), cook("blend", 0, 3, "Strain and sweeten")],
    t(2, 0, 5, 2), 2, 6, 300, 40, [...NG, "drink", "healthy"], { food: 6, water: 35, energy: 4 }, "npc", { from: "hawker" }),
  R("chapman", "Chapman", "🍹", "Nigerian", "drink", [n("soda"), n("orange"), n("lime"), n("ice")],
    [chop("Slice orange and lime"), prep("mix", "Mix over ice")], t(0, 0, 7, 4), 1, 2, 1500, 10, [...NG, "drink", "sweet"], { food: 2, water: 40, stress: -3 }, "book", { from: "Abuja Kitchen Bible" }),
  R("kelewele", "Kelewele", "🍌", "West African", "snack", [n("plantain", 2), n("ginger"), n("chili"), n("veg_oil")],
    [chop("Cube the plantain"), prep("marinate", "Toss in ginger and chili"), cook("deepfry", 175, 6, "Fry crisp")],
    t(6, 3, 4, 0), 2, 3, 700, 45, ["street", "spicy", "vegetarian"], { food: 25, energy: 5 }, "book", { from: "World Kitchen" }),

  // ── International ──
  R("bolognese", "Spaghetti bolognese", "🍝", "Italian", "main", [n("pasta", 2), n("beef"), n("tomato", 2), n("onion"), n("garlic"), n("olive_oil"), n("herbs")],
    [chop("Mince onion and garlic"), cook("saute", 160, 10, "Brown the beef"), cook("simmer", 95, 30, "Simmer the sauce"), cook("boil", 100, 10, "Cook the pasta al dente"), season(), plate()],
    t(1, 5, 2, 3), 3, 4, 2500, 55, [...FOREIGN, "meat", "comfort"], { food: 42, energy: 6 }, "book", { from: "World Kitchen" }),
  R("chicken_pasta", "Creamy chicken pasta", "🍝", "Italian", "main", [n("pasta", 2), n("chicken"), n("cream"), n("garlic"), n("cheese"), n("butter")],
    [chop("Slice the chicken"), cook("saute", 170, 10, "Sear the chicken"), cook("simmer", 90, 6, "Make the cream sauce"), cook("boil", 100, 10, "Cook the pasta"), season(), plate()],
    t(1, 5, 1, 0), 3, 3, 3200, 50, [...FOREIGN, "comfort", "meat"], { food: 45, energy: 6, stress: -4 }, "book", { from: "World Kitchen" }),
  R("pizza", "Pizza margherita", "🍕", "Italian", "main", [n("flour", 2), n("yeast"), n("tomato_paste"), n("cheese"), n("basil"), n("olive_oil")],
    [prep("knead", "Knead the dough"), cook("ferment", 30, 60, "Let the dough rise"), prep("mix", "Spread sauce and cheese"), cook("bake", 260, 10, "Bake very hot"), plate()],
    t(1, 5, 2, 2), 4, 4, 3500, 40, [...FOREIGN, "comfort"], { food: 40, energy: 5, stress: -4 }, "class"),
  R("burger", "Burger and fries", "🍔", "American", "main", [n("beef"), n("bread"), n("lettuce"), n("tomato"), n("cheese"), n("potato", 2), n("veg_oil")],
    [chop("Cut the fries and slice the tomato"), cook("grill", 220, 8, "Grill the patty"), cook("deepfry", 180, 7, "Fry the chips"), season(), plate("Build the burger")],
    t(2, 6, 2, 1), 3, 2, 3500, 35, [...FOREIGN, "fast", "meat", "comfort"], { food: 45, energy: 4, stress: -4 }, "book", { from: "World Kitchen" }),
  R("fried_chicken", "Crispy fried chicken", "🍗", "American", "main", [n("chicken", 2), n("flour"), n("paprika"), n("veg_oil")],
    [prep("marinate", "Season the chicken"), prep("mix", "Dredge in spiced flour"), cook("deepfry", 175, 14, "Fry until crisp and cooked through"), plate()],
    t(4, 6, 0, 0), 3, 3, 3000, 35, [...FOREIGN, "fast", "meat"], { food: 40, energy: 4, stress: -3 }, "book", { from: "World Kitchen" }),
  R("pancakes", "Pancakes", "🥞", "American", "breakfast", [n("flour"), n("eggs"), n("milk"), n("sugar"), n("butter")],
    [prep("mix", "Whisk the batter"), cook("fry", 160, 8, "Cook until bubbles form, then flip"), plate("Stack and drizzle")],
    t(0, 1, 6, 0), 2, 3, 1500, 35, [...FOREIGN, "breakfast", "sweet"], { food: 30, energy: 7, stress: -2 }, "book", { from: "Baking 101" }),
  R("full_breakfast", "Full English breakfast", "🍳", "British", "breakfast", [n("eggs", 2), n("bread"), n("beans"), n("pork"), n("mushroom"), n("tomato")],
    [chop("Halve tomatoes, slice mushrooms"), cook("fry", 170, 12, "Fry sausages, eggs and mushrooms"), cook("simmer", 90, 5, "Warm the beans"), plate()],
    t(1, 6, 1, 1), 2, 2, 3500, 50, [...FOREIGN, "breakfast", "meat"], { food: 45, energy: 10 }, "book", { from: "World Kitchen" }),
  R("fish_chips", "Fish and chips", "🐟", "British", "main", [n("fish"), n("potato", 2), n("flour"), n("veg_oil")],
    [chop("Cut thick chips"), prep("mix", "Make the batter"), cook("deepfry", 180, 10, "Fry the fish and chips"), season(), plate()],
    t(1, 6, 0, 2), 3, 2, 3000, 40, [...FOREIGN, "seafood", "comfort"], { food: 42, energy: 5 }, "book", { from: "World Kitchen" }),
  R("omelette", "Omelette", "🍳", "French", "breakfast", [n("eggs", 3), n("butter"), n("cheese"), n("mushroom")],
    [chop("Slice the mushrooms"), prep("mix", "Beat the eggs"), cook("fry", 150, 4, "Cook gently, fold"), season(), plate()],
    t(1, 4, 0, 0), 2, 1, 1500, 60, [...FOREIGN, "breakfast"], { food: 30, energy: 9 }, "basic"),
  R("crepes", "Crêpes", "🥞", "French", "dessert", [n("flour"), n("eggs"), n("milk"), n("butter"), n("sugar")],
    [prep("mix", "Whisk a thin batter"), cook("fry", 180, 6, "Swirl thin, flip once"), plate("Fold with sugar and lemon")],
    t(0, 1, 6, 1), 3, 4, 1800, 30, [...FOREIGN, "dessert", "sweet"], { food: 22, energy: 5, stress: -3 }, "book", { from: "Baking 101" }),
  R("chicken_curry", "Chicken curry and rice", "🍛", "Indian", "main", [n("chicken", 2), n("curry"), n("onion"), n("garlic"), n("ginger"), n("tomato"), n("coconut_milk"), n("basmati")],
    [chop("Dice onion, garlic and ginger"), cook("fry", 170, 8, "Bloom the spices"), cook("simmer", 95, 25, "Simmer the chicken in the sauce"), cook("boil", 100, 12, "Cook the rice"), season(), plate()],
    t(6, 5, 2, 1), 3, 4, 3000, 60, [...FOREIGN, "spicy", "meat"], { food: 45, energy: 6, stress: -3 }, "book", { from: "World Kitchen" }),
  R("biryani", "Chicken biryani", "🍚", "Indian", "main", [n("basmati", 2), n("chicken"), n("yogurt"), n("onion"), n("ginger"), n("garlic"), n("curry")],
    [prep("marinate", "Marinate the chicken in yogurt"), cook("fry", 170, 10, "Fry onions till dark gold"), cook("steam", 100, 25, "Layer and steam (dum)"), season(), plate()],
    t(6, 5, 1, 1), 4, 4, 4000, 60, [...FOREIGN, "spicy", "meat", "luxury"], { food: 45, energy: 6, stress: -4 }, "class"),
  R("stir_fry", "Chicken stir-fry noodles", "🥡", "Chinese", "main", [n("noodles", 2), n("chicken"), n("pepper"), n("carrot"), n("cabbage"), n("soy_sauce"), n("garlic"), n("ginger")],
    [chop("Julienne the vegetables"), cook("boil", 100, 4, "Blanch the noodles"), cook("saute", 220, 6, "Stir-fry everything very hot"), season(), plate()],
    t(3, 6, 2, 1), 3, 3, 2500, 60, [...FOREIGN, "fast", "meat"], { food: 40, energy: 6 }, "book", { from: "World Kitchen" }),
  R("ramen", "Ramen", "🍜", "Japanese", "soup", [n("noodles", 2), n("eggs"), n("chicken"), n("soy_sauce"), n("mushroom"), n("onion")],
    [cook("simmer", 95, 60, "Make a rich broth"), cook("boil", 100, 7, "Soft-boil the eggs"), cook("boil", 100, 4, "Cook the noodles"), season(), plate("Arrange toppings carefully")],
    t(2, 7, 1, 0), 4, 2, 4000, 55, [...FOREIGN, "comfort"], { food: 40, water: 10, energy: 6, stress: -5 }, "class"),
  R("sushi", "Sushi platter", "🍣", "Japanese", "main", [n("rice", 2), n("fish"), n("vinegar"), n("cucumber"), n("avocado")],
    [cook("boil", 100, 15, "Cook the rice and season with vinegar"), chop("Slice the fish razor thin"), prep("mix", "Roll and shape"), plate("Arrange the platter")],
    t(0, 4, 3, 4), 5, 3, 6000, 65, [...FOREIGN, "seafood", "luxury", "healthy"], { food: 35, energy: 6 }, "secret"),
  R("bibimbap", "Bibimbap", "🍲", "Korean", "main", [n("rice", 2), n("beef"), n("spinach"), n("carrot"), n("eggs"), n("chili"), n("soy_sauce")],
    [chop("Julienne carrots, blanch spinach"), cook("fry", 200, 6, "Sear the beef"), cook("fry", 160, 3, "Fry an egg"), season(), plate("Arrange in sections over rice")],
    t(5, 5, 2, 1), 3, 2, 3500, 70, [...FOREIGN, "spicy", "healthy"], { food: 42, energy: 7 }, "book", { from: "World Kitchen" }),
  R("tacos", "Beef tacos", "🌮", "Mexican", "main", [n("tortilla"), n("beef"), n("tomato"), n("onion"), n("chili"), n("lime")],
    [chop("Dice tomato and onion for salsa"), cook("fry", 200, 8, "Cook the spiced beef"), season(), plate("Fill and finish with lime")],
    t(6, 5, 1, 3), 2, 3, 2500, 45, [...FOREIGN, "spicy", "street", "meat"], { food: 35, energy: 5 }, "book", { from: "World Kitchen" }),
  R("shawarma", "Chicken shawarma", "🌯", "Middle Eastern", "main", [n("tortilla"), n("chicken"), n("cabbage"), n("mayonnaise"), n("garlic")],
    [chop("Shred the cabbage"), prep("marinate", "Marinate the chicken"), cook("grill", 210, 10, "Grill the chicken"), prep("mix", "Make the garlic sauce"), plate("Wrap tight")],
    t(3, 5, 1, 2), 2, 2, 3000, 40, [...FOREIGN, "street", "fast", "meat"], { food: 40, energy: 5, stress: -3 }, "book", { from: "World Kitchen" }),
  R("greek_salad", "Greek salad", "🥗", "Mediterranean", "side", [n("lettuce"), n("tomato"), n("cucumber"), n("cheese"), n("olive_oil"), n("onion"), n("lemon")],
    [chop("Chop everything into chunks"), prep("mix", "Dress with oil and lemon"), season(), plate()],
    t(1, 4, 1, 4), 1, 2, 2000, 90, [...FOREIGN, "healthy", "vegetarian"], { food: 18, water: 8, energy: 6, health: 2 }, "book", { from: "World Kitchen" }),
  R("fruit_salad", "Fruit salad", "🍉", "Nigerian", "dessert", [n("banana"), n("pineapple"), n("mango"), n("watermelon")],
    [chop("Cube all the fruit"), plate("Serve chilled")], t(0, 0, 6, 2), 1, 3, 1200, 95, ["healthy", "sweet", "vegetarian", "dessert"], { food: 15, water: 15, energy: 6, health: 2 }, "basic"),

  // ── Baking & desserts ──
  R("bread_loaf", "Homemade bread", "🍞", "British", "baked", [n("flour", 3), n("yeast"), n("sugar"), n("butter"), n("milk"), n("salt")],
    [prep("knead", "Knead for ten minutes"), cook("ferment", 30, 60, "First rise"), cook("bake", 200, 30, "Bake until it sounds hollow")],
    t(0, 3, 2, 0), 3, 8, 400, 40, ["baked", "breakfast"], { food: 18, energy: 5 }, "book", { from: "Baking 101" }),
  R("sponge_cake", "Sponge cake", "🍰", "British", "dessert", [n("flour", 2), n("eggs", 2), n("butter"), n("sugar"), n("baking_powder"), n("milk")],
    [prep("mix", "Cream butter and sugar, beat in eggs"), cook("bake", 180, 25, "Bake without opening the door"), plate("Decorate")],
    t(0, 1, 7, 0), 3, 8, 1000, 25, ["baked", "dessert", "sweet"], { food: 18, energy: 5, stress: -4 }, "book", { from: "Baking 101" }),
  R("chocolate_cake", "Chocolate cake", "🎂", "American", "dessert", [n("flour", 2), n("eggs", 2), n("butter"), n("sugar"), n("cocoa"), n("chocolate"), n("baking_powder")],
    [prep("mix", "Mix the batter"), cook("bake", 175, 35, "Bake low and even"), prep("mix", "Make the ganache"), plate("Decorate the cake")],
    t(0, 1, 8, 0), 4, 8, 1500, 20, ["baked", "dessert", "sweet", "luxury"], { food: 20, energy: 5, stress: -6 }, "book", { from: "Baking 101" }),
  R("cookies", "Chocolate chip cookies", "🍪", "American", "dessert", [n("flour"), n("butter"), n("sugar"), n("eggs"), n("chocolate")],
    [prep("mix", "Cream the butter and sugar"), cook("bake", 180, 12, "Bake till edges are golden")],
    t(0, 2, 7, 0), 2, 10, 400, 20, ["baked", "dessert", "sweet"], { food: 10, energy: 4, stress: -3 }, "book", { from: "Baking 101" }),
  R("donuts", "Donuts", "🍩", "American", "dessert", [n("flour", 2), n("yeast"), n("sugar"), n("milk"), n("eggs"), n("veg_oil")],
    [prep("knead", "Knead a soft dough"), cook("ferment", 30, 45, "Let them rise"), cook("deepfry", 175, 6, "Fry and flip"), plate("Glaze them")],
    t(0, 1, 8, 0), 3, 8, 600, 15, ["baked", "dessert", "sweet"], { food: 14, energy: 5, stress: -3 }, "book", { from: "Baking 101" }),
  R("croissants", "Croissants", "🥐", "French", "baked", [n("flour", 2), n("butter", 2), n("yeast"), n("milk"), n("sugar")],
    [prep("knead", "Laminate butter into the dough, fold three times"), cook("ferment", 28, 90, "Prove slowly"), cook("bake", 200, 18, "Bake until flaky")],
    t(0, 2, 3, 0), 5, 8, 1200, 20, [...FOREIGN, "baked", "luxury", "breakfast"], { food: 16, energy: 5, stress: -3 }, "class"),
  R("cupcakes", "Cupcakes", "🧁", "American", "dessert", [n("flour"), n("eggs"), n("butter"), n("sugar"), n("cream")],
    [prep("mix", "Mix the batter"), cook("bake", 180, 18, "Bake in cases"), plate("Pipe the frosting")],
    t(0, 1, 8, 0), 3, 12, 600, 15, ["baked", "dessert", "sweet"], { food: 10, energy: 4, stress: -4 }, "book", { from: "Baking 101" }),
  R("cheesecake", "Cheesecake", "🍰", "American", "dessert", [n("cheese", 2), n("cream"), n("sugar"), n("eggs"), n("butter"), n("flour")],
    [prep("mix", "Make the biscuit base"), prep("mix", "Beat the filling smooth"), cook("bake", 150, 50, "Bake low and slow"), plate()],
    t(0, 2, 7, 2), 4, 8, 2000, 20, ["baked", "dessert", "sweet", "luxury"], { food: 18, energy: 4, stress: -6 }, "class"),
  R("ice_cream", "Vanilla ice cream", "🍨", "Italian", "dessert", [n("cream", 2), n("milk"), n("sugar"), n("vanilla")],
    [prep("mix", "Make the custard"), cook("freeze", -18, 240, "Churn and freeze")],
    t(0, 1, 8, 0), 3, 6, 1200, 15, ["dessert", "sweet"], { food: 12, water: 5, stress: -6 }, "book", { from: "Baking 101" }),
  R("chocolate_mousse", "Chocolate mousse", "🍫", "French", "dessert", [n("chocolate", 2), n("cream"), n("eggs", 2), n("sugar")],
    [prep("mix", "Whip the cream and whites separately"), prep("mix", "Fold gently into the chocolate"), cook("freeze", 4, 120, "Chill to set"), plate()],
    t(0, 1, 7, 0), 4, 4, 2500, 15, [...FOREIGN, "dessert", "luxury", "sweet"], { food: 14, stress: -7 }, "class"),
  R("apple_pie", "Apple pie", "🥧", "American", "dessert", [n("flour", 2), n("butter"), n("apple", 2), n("sugar"), n("cinnamon")],
    [chop("Slice the apples"), prep("knead", "Make the pastry"), cook("bake", 190, 40, "Bake until bubbling")],
    t(0, 1, 7, 2), 3, 6, 1500, 30, ["baked", "dessert", "sweet"], { food: 18, energy: 4, stress: -5 }, "book", { from: "Baking 101" }),

  // ── Drinks ──
  R("coffee", "Black coffee", "☕", "American", "drink", [n("coffee")], [cook("brew", 95, 4, "Brew")], t(0, 0, 1, 2), 1, 2, 800, 5, ["drink", "breakfast"], { water: 25, energy: 12 }, "basic"),
  R("espresso", "Espresso", "☕", "Italian", "drink", [n("coffee")], [cook("espresso", 93, 1, "Pull a shot")], t(0, 0, 0, 2), 2, 1, 1200, 5, [...FOREIGN, "drink"], { water: 5, energy: 14 }, "book", { from: "Café Guide" }),
  R("cappuccino", "Cappuccino", "☕", "Italian", "drink", [n("coffee"), n("milk")], [cook("espresso", 93, 1, "Pull a shot"), prep("mix", "Steam and foam the milk")], t(0, 0, 2, 1), 3, 1, 2000, 15, [...FOREIGN, "drink"], { water: 15, energy: 12, stress: -2 }, "book", { from: "Café Guide" }),
  R("latte", "Latte", "☕", "Italian", "drink", [n("coffee"), n("milk", 2), n("sugar")], [cook("espresso", 93, 1, "Pull a shot"), prep("mix", "Steam the milk silky"), plate("Pour latte art")], t(0, 0, 4, 0), 3, 1, 2200, 15, [...FOREIGN, "drink"], { water: 20, energy: 10, stress: -2 }, "book", { from: "Café Guide" }),
  R("iced_coffee", "Iced coffee", "🧋", "American", "drink", [n("coffee"), n("milk"), n("ice"), n("sugar")], [cook("brew", 95, 4, "Brew strong"), prep("mix", "Pour over ice")], t(0, 0, 5, 1), 2, 1, 2000, 10, [...FOREIGN, "drink"], { water: 25, energy: 10, stress: -2 }, "book", { from: "Café Guide" }),
  R("smoothie", "Banana-strawberry smoothie", "🥤", "American", "drink", [n("banana"), n("strawberry"), n("yogurt"), n("honey")], [chop("Slice the fruit"), cook("blend", 0, 2, "Blend smooth")], t(0, 0, 6, 2), 1, 2, 2000, 80, ["drink", "healthy", "sweet"], { food: 10, water: 30, energy: 7, health: 1 }, "book", { from: "Café Guide" }),
  R("lemonade", "Fresh lemonade", "🍋", "American", "drink", [n("lemon", 2), n("sugar"), n("ice")], [prep("mix", "Squeeze and stir")], t(0, 0, 6, 7), 1, 4, 800, 20, ["drink", "sweet"], { water: 40, stress: -2 }, "basic"),
  R("orange_juice", "Fresh orange juice", "🍊", "Nigerian", "drink", [n("orange", 3)], [cook("juice", 0, 3, "Juice the oranges")], t(0, 0, 5, 4), 1, 2, 1000, 70, ["drink", "healthy"], { water: 35, energy: 6, health: 1 }, "basic"),
  R("milkshake", "Vanilla milkshake", "🥤", "American", "drink", [n("milk", 2), n("cream"), n("sugar"), n("vanilla")], [cook("blend", 0, 2, "Blend thick")], t(0, 0, 8, 0), 2, 2, 2000, 15, ["drink", "sweet", "dessert"], { food: 12, water: 25, stress: -4 }, "book", { from: "Café Guide" }),
  R("mocktail", "Abuja Sunset mocktail", "🍹", "Fusion", "drink", [n("pineapple"), n("orange"), n("zobo_leaf"), n("lime"), n("sugar"), n("ice")],
    [chop("Cut the fruit"), cook("boil", 100, 10, "Make a zobo syrup"), cook("blend", 0, 2, "Blend the fruit"), plate("Layer it like a sunset")],
    t(0, 0, 6, 5), 3, 2, 2500, 35, ["drink", "luxury", "sweet"], { water: 40, stress: -4 }, "secret"),

  // ── Fusion: discovered by experimenting ──
  R("suya_pasta", "Suya pasta", "🍝", "Fusion", "main", [n("pasta", 2), n("suya_beef"), n("suya_spice"), n("pepper"), n("onion"), n("cream")],
    [chop("Slice beef and peppers"), cook("grill", 220, 8, "Grill the suya"), cook("boil", 100, 10, "Cook the pasta"), cook("simmer", 90, 5, "Toss in a creamy yaji sauce"), season(), plate()],
    t(7, 5, 1, 0), 4, 3, 4000, 45, ["spicy", "meat", "comfort"], { food: 45, energy: 6, stress: -5 }, "experiment", { blurb: "Northern heat meets Italian comfort." }),
  R("seafood_jollof", "Seafood jollof", "🦐", "Fusion", "main", [n("rice", 2), n("tomato", 2), n("pepper"), n("scotch_bonnet"), n("prawns"), n("fish"), n("stock")],
    [cook("blend", 0, 3, "Blend the base"), cook("fry", 175, 12, "Fry the base"), cook("simmer", 110, 25, "Simmer the rice"), cook("saute", 200, 4, "Flash-cook the prawns"), season(), plate()],
    t(6, 5, 2, 2), 4, 4, 4500, 60, ["spicy", "seafood", "luxury", "local"], { food: 45, energy: 6, stress: -5 }, "experiment"),
  R("zobo_chicken", "Zobo-glazed chicken", "🍗", "Fusion", "main", [n("chicken", 2), n("zobo_leaf"), n("honey"), n("ginger"), n("garlic")],
    [cook("boil", 100, 15, "Reduce zobo into a glaze"), prep("marinate", "Coat the chicken"), cook("roast", 200, 35, "Roast, basting twice"), plate()],
    t(2, 4, 6, 4), 4, 3, 4000, 50, ["sweet", "meat", "luxury"], { food: 38, energy: 5, stress: -4 }, "experiment"),
  R("pepper_soup_ramen", "Pepper soup ramen", "🍜", "Fusion", "soup", [n("noodles", 2), n("goat"), n("pepper_soup_spice"), n("scent_leaf"), n("eggs")],
    [cook("boil", 100, 40, "Make a pepper soup broth"), cook("boil", 100, 7, "Soft-boil the eggs"), cook("boil", 100, 4, "Cook the noodles"), season(), plate()],
    t(8, 6, 0, 1), 4, 2, 4000, 55, ["spicy", "comfort", "meat"], { food: 40, water: 10, energy: 6, stress: -6 }, "experiment"),
  R("plantain_waffles", "Plantain waffles", "🧇", "Fusion", "breakfast", [n("plantain", 2), n("flour"), n("eggs"), n("milk"), n("cinnamon")],
    [prep("pound", "Mash the ripe plantain"), prep("mix", "Mix the batter"), cook("bake", 190, 6, "Cook in the waffle iron"), plate("Drizzle with honey")],
    t(0, 1, 7, 0), 3, 4, 2000, 40, ["breakfast", "sweet"], { food: 28, energy: 7, stress: -3 }, "experiment"),
];

export const recipe = (id: string) => RECIPES.find((r) => r.id === id);

/** Cookbooks sold at the Jabi Lake Mall bookshop. */
export const BOOKS = [
  { id: "Abuja Kitchen Bible", price: 8000, blurb: "Nigerian classics from soups to street food." },
  { id: "World Kitchen", price: 15000, blurb: "Italian, American, British, Indian, Chinese, Korean, Mexican and more." },
  { id: "Baking 101", price: 10000, blurb: "Bread, cakes, pastries, cookies and desserts." },
  { id: "Café Guide", price: 12000, blurb: "Coffee, smoothies and café drinks." },
];

/** Cooking classes: a fee, some time, and the recipes taught. */
export const CLASSES = [
  { id: "class_pro", title: "Professional kitchen class", price: 60000, recipes: ["catfish_pepper_soup", "pizza", "biryani", "ramen"] },
  { id: "class_pastry", title: "Pastry masterclass", price: 80000, recipes: ["croissants", "cheesecake", "chocolate_mousse"] },
];
