import { chromium } from "playwright";
import fs from "fs";
const S = "/tmp/claude-0/-home-user-midnry/062416c4-9daa-5d37-8179-aae4f45cf419/scratchpad";
const base = JSON.parse(fs.readFileSync(`${S}/save.json`, "utf8"));
const [tag, w, h] = [process.argv[2], +process.argv[3], +process.argv[4]];
const st = { ...base, mapVersion: 4, name: "Ada", background: "average", stage: "primary", chapter: "primary", scene: "end", result: null, pendingNext: null, age: 9, day: 1, slot: 0, event: null, toast: null, minigame: null, social: null, flags: {}, emekaMeet: false, nepoMeet: null };
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ viewport: { width: w, height: h }, hasTouch: w < 600, isMobile: w < 600 });
await ctx.addInitScript((v) => { if (!sessionStorage.getItem("s")) { localStorage.setItem("abuja-hustle.save.v1", v); sessionStorage.setItem("s", "1"); } localStorage.setItem("abuja-hustle.age-ok", "yes"); }, JSON.stringify(st));
const p = await ctx.newPage(); const errs = [];
let reqs = []; let t0 = 0;
p.on("request", (r) => t0 && reqs.push({ u: r.url().replace(/^https?:\/\/[^/]+/, ""), t: Date.now() - t0 }));
p.on("requestfinished", (r) => { if (!t0) return; const e = reqs.find((x) => x.u === r.url().replace(/^https?:\/\/[^/]+/, "") && x.d == null); if (e) e.d = Date.now() - t0; });
p.on("pageerror", (e) => errs.push(e.stack)); p.on("console", (m) => { if (m.type() === "error" && !/CERT|RETRIES|fonts/.test(m.text())) errs.push(m.text().slice(0, 200)); });
await p.goto("http://127.0.0.1:8080/games/abuja-hustle", { waitUntil: "networkidle" }); await p.waitForTimeout(1500);
await p.evaluate(() => [...document.querySelectorAll("button")].find((b) => /^Continue$/.test(b.textContent))?.click());
await p.waitForFunction(() => window.__abuja, null, { timeout: 60000 });
await p.waitForFunction(() => !document.querySelector(".abuja-loading"), null, { timeout: 60000 });
await p.waitForTimeout(2000);
await p.evaluate(() => window.__abuja.place(710, 490)); await p.waitForTimeout(1200);
await p.screenshot({ path: `${S}/shots/${tag}-primary-end.png` });
await p.locator("button.h-12.rounded-full").first().evaluate((el) => el.click()); await p.waitForTimeout(1200);
t0 = Date.now();
await p.getByRole("button", { name: /On to secondary school/ }).first().evaluate((el) => el.click());
const samples = [];
for (let i = 0; i < 60; i++) {
  await p.waitForTimeout(500);
  const info = await p.evaluate(() => ({ load: !!document.querySelector(".abuja-loading"), status: document.querySelector(".abuja-loading__status")?.textContent?.trim().slice(0, 80) ?? "", btns: [...document.querySelectorAll("button")].map((b) => b.textContent.trim()).filter(Boolean).slice(0, 8).join(" | ").slice(0, 200) }));
  samples.push({ t: Date.now() - t0, ...info });
  if (i === 6) await p.screenshot({ path: `${S}/shots/${tag}-sec-3s.png` });
  if (!info.load && i > 4 && samples.filter((s) => !s.load).length > 4) break;
}
await p.screenshot({ path: `${S}/shots/${tag}-sec-done.png` });
for (const s of samples.filter((_, i) => i % 2 === 0)) console.log(s.t, s.load ? "LOADING" : "ready", s.status, "::", s.btns);
const slow = reqs.filter((r) => (r.d ?? 99999) - r.t > 800).slice(0, 15);
console.log("requests", reqs.length, "unfinished", reqs.filter((r) => r.d == null).length);
console.log("slow", JSON.stringify(slow, null, 0));
console.log("last finished", Math.max(...reqs.map((r) => r.d ?? 0)));
const kinds = {}; for (const r of reqs) { const k = r.u.split("/").slice(0, 3).join("/"); kinds[k] = (kinds[k] ?? 0) + 1; } console.log(kinds);
console.log(tag, "errors", JSON.stringify(errs));
await b.close();
