/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as EverydayRouteImport } from './routes/everyday'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsSlugRouteImport } from './routes/apps/$slug'
import { Route as AudiencesAudienceRouteImport } from './routes/audiences/$audience'
import { Route as ForAudienceRouteImport } from './routes/for/$audience'
import { Route as SectionsGenreRouteImport } from './routes/sections/$genre'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAvatarIdRouteImport } from './routes/api/avatar/$id'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as ApiRemindCalendarTokenRouteImport } from './routes/api/remind/calendar/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const EverydayRoute = EverydayRouteImport.update({
  id: '/everyday',
  path: '/everyday',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiencesAudienceRoute = AudiencesAudienceRouteImport.update({
  id: '/audiences/$audience',
  path: '/audiences/$audience',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAudienceRoute = ForAudienceRouteImport.update({
  id: '/for/$audience',
  path: '/for/$audience',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsGenreRoute = SectionsGenreRouteImport.update({
  id: '/sections/$genre',
  path: '/sections/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarIdRoute = ApiAvatarIdRouteImport.update({
  id: '/api/avatar/$id',
  path: '/api/avatar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindCalendarTokenRoute = ApiRemindCalendarTokenRouteImport.update({
  id: '/api/remind/calendar/$token',
  path: '/api/remind/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/billing': typeof BillingRoute
  '/earnings': typeof EarningsRoute
  '/everyday': typeof EverydayRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/review': typeof ReviewRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/audiences/$audience': typeof AudiencesAudienceRoute
  '/for/$audience': typeof ForAudienceRoute
  '/sections/$genre': typeof SectionsGenreRoute
  '/apps/': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$id': typeof ApiAvatarIdRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/remind/calendar/$token': typeof ApiRemindCalendarTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/billing': typeof BillingRoute
  '/earnings': typeof EarningsRoute
  '/everyday': typeof EverydayRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/review': typeof ReviewRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/audiences/$audience': typeof AudiencesAudienceRoute
  '/for/$audience': typeof ForAudienceRoute
  '/sections/$genre': typeof SectionsGenreRoute
  '/apps': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$id': typeof ApiAvatarIdRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/remind/calendar/$token': typeof ApiRemindCalendarTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/billing': typeof BillingRoute
  '/earnings': typeof EarningsRoute
  '/everyday': typeof EverydayRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/review': typeof ReviewRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/audiences/$audience': typeof AudiencesAudienceRoute
  '/for/$audience': typeof ForAudienceRoute
  '/sections/$genre': typeof SectionsGenreRoute
  '/apps/': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$id': typeof ApiAvatarIdRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/remind/calendar/$token': typeof ApiRemindCalendarTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/billing'
    | '/earnings'
    | '/everyday'
    | '/login'
    | '/pricing'
    | '/review'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/submit'
    | '/apps/$slug'
    | '/audiences/$audience'
    | '/for/$audience'
    | '/sections/$genre'
    | '/apps/'
    | '/api/auth/$'
    | '/api/avatar/$id'
    | '/api/paystack/webhook'
    | '/api/remind/calendar/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/billing'
    | '/earnings'
    | '/everyday'
    | '/login'
    | '/pricing'
    | '/review'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/submit'
    | '/apps/$slug'
    | '/audiences/$audience'
    | '/for/$audience'
    | '/sections/$genre'
    | '/apps'
    | '/api/auth/$'
    | '/api/avatar/$id'
    | '/api/paystack/webhook'
    | '/api/remind/calendar/$token'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/billing'
    | '/earnings'
    | '/everyday'
    | '/login'
    | '/pricing'
    | '/review'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/submit'
    | '/apps/$slug'
    | '/audiences/$audience'
    | '/for/$audience'
    | '/sections/$genre'
    | '/apps/'
    | '/api/auth/$'
    | '/api/avatar/$id'
    | '/api/paystack/webhook'
    | '/api/remind/calendar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BillingRoute: typeof BillingRoute
  EarningsRoute: typeof EarningsRoute
  EverydayRoute: typeof EverydayRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ReviewRoute: typeof ReviewRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  AppsSlugRoute: typeof AppsSlugRoute
  AudiencesAudienceRoute: typeof AudiencesAudienceRoute
  ForAudienceRoute: typeof ForAudienceRoute
  SectionsGenreRoute: typeof SectionsGenreRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarIdRoute: typeof ApiAvatarIdRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  ApiRemindCalendarTokenRoute: typeof ApiRemindCalendarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/everyday': {
      id: '/everyday'
      path: '/everyday'
      fullPath: '/everyday'
      preLoaderRoute: typeof EverydayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiences/$audience': {
      id: '/audiences/$audience'
      path: '/audiences/$audience'
      fullPath: '/audiences/$audience'
      preLoaderRoute: typeof AudiencesAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/$audience': {
      id: '/for/$audience'
      path: '/for/$audience'
      fullPath: '/for/$audience'
      preLoaderRoute: typeof ForAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/$genre': {
      id: '/sections/$genre'
      path: '/sections/$genre'
      fullPath: '/sections/$genre'
      preLoaderRoute: typeof SectionsGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$id': {
      id: '/api/avatar/$id'
      path: '/api/avatar/$id'
      fullPath: '/api/avatar/$id'
      preLoaderRoute: typeof ApiAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remind/calendar/$token': {
      id: '/api/remind/calendar/$token'
      path: '/api/remind/calendar/$token'
      fullPath: '/api/remind/calendar/$token'
      preLoaderRoute: typeof ApiRemindCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BillingRoute: BillingRoute,
  EarningsRoute: EarningsRoute,
  EverydayRoute: EverydayRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ReviewRoute: ReviewRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  AppsSlugRoute: AppsSlugRoute,
  AudiencesAudienceRoute: AudiencesAudienceRoute,
  ForAudienceRoute: ForAudienceRoute,
  SectionsGenreRoute: SectionsGenreRoute,
  AppsIndexRoute: AppsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarIdRoute: ApiAvatarIdRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  ApiRemindCalendarTokenRoute: ApiRemindCalendarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
