/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsSlugRouteImport } from './routes/apps/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/earnings': typeof EarningsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/review': typeof ReviewRoute
  '/security': typeof SecurityRoute
  '/submit': typeof SubmitRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/earnings': typeof EarningsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/review': typeof ReviewRoute
  '/security': typeof SecurityRoute
  '/submit': typeof SubmitRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/apps': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/earnings': typeof EarningsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/review': typeof ReviewRoute
  '/security': typeof SecurityRoute
  '/submit': typeof SubmitRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/earnings'
    | '/login'
    | '/pricing'
    | '/review'
    | '/security'
    | '/submit'
    | '/apps/$slug'
    | '/apps/'
    | '/api/auth/$'
    | '/api/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/earnings'
    | '/login'
    | '/pricing'
    | '/review'
    | '/security'
    | '/submit'
    | '/apps/$slug'
    | '/apps'
    | '/api/auth/$'
    | '/api/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/earnings'
    | '/login'
    | '/pricing'
    | '/review'
    | '/security'
    | '/submit'
    | '/apps/$slug'
    | '/apps/'
    | '/api/auth/$'
    | '/api/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  EarningsRoute: typeof EarningsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ReviewRoute: typeof ReviewRoute
  SecurityRoute: typeof SecurityRoute
  SubmitRoute: typeof SubmitRoute
  AppsSlugRoute: typeof AppsSlugRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  EarningsRoute: EarningsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ReviewRoute: ReviewRoute,
  SecurityRoute: SecurityRoute,
  SubmitRoute: SubmitRoute,
  AppsSlugRoute: AppsSlugRoute,
  AppsIndexRoute: AppsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
